// src/utils/mockRecipes.js

export const mockRecipes = [
  // ── 6 recipe cũ (thiếu nguyên liệu) ──
  {
    id: 'recipe_1',
    title: 'Salad Gà Áp Chảo',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600',
    videoUrl: null,
    labels: ['Giữ dáng', 'Bữa trưa', 'High Protein'],
    macros: { protein: 35, carbs: 12, fat: 8, calories: 280 },
    cookTime: 20,
    servings: 2,
    difficulty: 'Dễ',
    author: { name: 'Chef Minh', avatar: 'https://i.pravatar.cc/150?u=chefminh' },
    ingredients: [
      { name: 'Ức gà', amount: '200g', calories: 220, protein: 46, carbs: 0, fat: 5, category: 'meat' },
      { name: 'Rau xà lách', amount: '100g', calories: 15, protein: 1, carbs: 3, fat: 0, category: 'vegetable' },
      { name: 'Cà chua bi', amount: '50g', calories: 10, protein: 0, carbs: 2, fat: 0, category: 'vegetable' },
      { name: 'Dầu olive', amount: '10ml', calories: 80, protein: 0, carbs: 0, fat: 9, category: 'condiment' },
      { name: 'Chanh', amount: '1/2 quả', calories: 10, protein: 0, carbs: 3, fat: 0, category: 'condiment' },
    ],
    steps: [
      { order: 1, description: 'Rửa sạch rau xà lách và cà chua bi, để ráo nước.', image: null },
      { order: 2, description: 'Ướp ức gà với ít muối, tiêu và 1 thìa dầu olive trong 10 phút.', image: null },
      { order: 3, description: 'Áp chảo ức gà trên chảo nóng 3-4 phút mỗi mặt.', image: null },
      { order: 4, description: 'Trộn rau, cà chua, thịt gà. Rưới dầu olive và nước chanh.', image: null },
    ],
    reviews: { avgRating: 4.5, total: 128 },
    isSaved: false,
  },
  {
    id: 'recipe_2',
    title: 'Cơm Gà Hải Nam',
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    labels: ['Bữa trưa', 'Bữa tối', 'Gia đình'],
    macros: { protein: 28, carbs: 55, fat: 15, calories: 480 },
    cookTime: 45,
    servings: 4,
    difficulty: 'Trung bình',
    author: { name: 'Chị Lan', avatar: 'https://i.pravatar.cc/150?u=lan' },
    ingredients: [
      { name: 'Gà ta', amount: '1 con (1.2kg)', calories: 1200, protein: 110, carbs: 0, fat: 80, category: 'meat' },
      { name: 'Gạo tẻ', amount: '400g', calories: 1400, protein: 28, carbs: 310, fat: 4, category: 'grain' },
      { name: 'Gừng', amount: '50g', calories: 20, protein: 0, carbs: 4, fat: 0, category: 'condiment' },
      { name: 'Hành lá', amount: '30g', calories: 10, protein: 0, carbs: 2, fat: 0, category: 'vegetable' },
      { name: 'Dầu ăn', amount: '30ml', calories: 240, protein: 0, carbs: 0, fat: 27, category: 'condiment' },
      { name: 'Tỏi', amount: '20g', calories: 30, protein: 1, carbs: 7, fat: 0, category: 'condiment' },
    ],
    steps: [
      { order: 1, description: 'Làm sạch gà, bóp muối và gừng đập dập khử mùi.', image: null },
      { order: 2, description: 'Luộc gà 25 phút, ngâm ngay vào nước đá.', image: null },
      { order: 3, description: 'Phi tỏi, cho gạo vào xào sơ. Nấu cơm bằng nước luộc gà.', image: null },
      { order: 4, description: 'Xếp cơm ra đĩa, thái gà. Rắc hành lá.', image: null },
    ],
    reviews: { avgRating: 4.8, total: 342 },
    isSaved: true,
  },
  {
    id: 'recipe_3',
    title: 'Sinh Tố Bơ Sữa Chua',
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=600',
    videoUrl: null,
    labels: ['Giữ dáng', 'Bữa sáng', 'Bữa phụ', 'Nhanh gọn'],
    macros: { protein: 8, carbs: 18, fat: 12, calories: 220 },
    cookTime: 5,
    servings: 1,
    difficulty: 'Dễ',
    author: { name: 'FitFoodie', avatar: 'https://i.pravatar.cc/150?u=fit' },
    ingredients: [
      { name: 'Bơ', amount: '1/2 quả', calories: 160, protein: 2, carbs: 9, fat: 15, category: 'vegetable' },
      { name: 'Sữa chua không đường', amount: '100g', calories: 60, protein: 6, carbs: 8, fat: 0, category: 'dairy' },
      { name: 'Sữa tươi', amount: '100ml', calories: 65, protein: 3, carbs: 5, fat: 3, category: 'dairy' },
      { name: 'Mật ong', amount: '10g', calories: 30, protein: 0, carbs: 8, fat: 0, category: 'condiment' },
    ],
    steps: [
      { order: 1, description: 'Bơ bổ đôi, bỏ hạt, dùng thìa múc thịt ra cối xay.', image: null },
      { order: 2, description: 'Cho tất cả nguyên liệu vào máy xay sinh tố, xay nhuyễn 30 giây.', image: null },
      { order: 3, description: 'Đổ ra ly, có thể thêm đá.', image: null },
    ],
    reviews: { avgRating: 4.2, total: 89 },
    isSaved: false,
  },
  {
    id: 'recipe_4',
    title: 'Cá Hồi Sốt Bơ Tỏi',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600',
    videoUrl: null,
    labels: ['Tăng cơ', 'Bữa tối', 'Keto'],
    macros: { protein: 42, carbs: 4, fat: 28, calories: 450 },
    cookTime: 25,
    servings: 2,
    difficulty: 'Trung bình',
    author: { name: 'Chef Khoa', avatar: 'https://i.pravatar.cc/150?u=khoa' },
    ingredients: [
      { name: 'Cá hồi fillet', amount: '300g', calories: 360, protein: 40, carbs: 0, fat: 22, category: 'meat' },
      { name: 'Bơ', amount: '1/2 quả', calories: 160, protein: 2, carbs: 9, fat: 15, category: 'vegetable' },
      { name: 'Tỏi', amount: '15g', calories: 22, protein: 1, carbs: 5, fat: 0, category: 'condiment' },
      { name: 'Chanh', amount: '1 quả', calories: 20, protein: 0, carbs: 6, fat: 0, category: 'condiment' },
      { name: 'Dầu olive', amount: '15ml', calories: 120, protein: 0, carbs: 0, fat: 14, category: 'condiment' },
      { name: 'Rau cải bó xôi', amount: '100g', calories: 23, protein: 3, carbs: 4, fat: 0, category: 'vegetable' },
    ],
    steps: [
      { order: 1, description: 'Rửa cá hồi, thấm khô. Ướp với muối, tiêu, nước cốt chanh.', image: null },
      { order: 2, description: 'Áp chảo cá hồi 4 phút mỗi mặt.', image: null },
      { order: 3, description: 'Phi tỏi, cho bơ nghiền vào đảo đều.', image: null },
      { order: 4, description: 'Xếp cá ra đĩa, chan sốt bơ tỏi lên.', image: null },
    ],
    reviews: { avgRating: 4.6, total: 215 },
    isSaved: false,
  },
  {
    id: 'recipe_5',
    title: 'Pancake Yến Mạch Chuối',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    labels: ['Bữa sáng', 'Giữ dáng', 'Trẻ em', 'Bữa phụ'],
    macros: { protein: 12, carbs: 45, fat: 6, calories: 310 },
    cookTime: 15,
    servings: 2,
    difficulty: 'Dễ',
    author: { name: 'Mẹ Bun', avatar: 'https://i.pravatar.cc/150?u=bun' },
    ingredients: [
      { name: 'Yến mạch', amount: '80g', calories: 300, protein: 10, carbs: 54, fat: 5, category: 'grain' },
      { name: 'Chuối', amount: '1 quả', calories: 90, protein: 1, carbs: 23, fat: 0, category: 'vegetable' },
      { name: 'Trứng gà', amount: '2 quả', calories: 140, protein: 12, carbs: 1, fat: 10, category: 'dairy' },
      { name: 'Sữa tươi', amount: '50ml', calories: 32, protein: 2, carbs: 2, fat: 1, category: 'dairy' },
      { name: 'Mật ong', amount: '15g', calories: 45, protein: 0, carbs: 12, fat: 0, category: 'condiment' },
    ],
    steps: [
      { order: 1, description: 'Nghiền chuối bằng nĩa trong tô lớn.', image: null },
      { order: 2, description: 'Thêm yến mạch, trứng, sữa. Khuấy đều.', image: null },
      { order: 3, description: 'Chiên từng muỗng hỗn hợp 2-3 phút mỗi mặt.', image: null },
      { order: 4, description: 'Xếp pancake chồng lên nhau, rưới mật ong.', image: null },
    ],
    reviews: { avgRating: 4.3, total: 156 },
    isSaved: true,
  },
  {
    id: 'recipe_6',
    title: 'Canh Rau Củ Thịt Bằm',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600',
    videoUrl: null,
    labels: ['Bữa tối', 'Gia đình', 'Dễ tiêu'],
    macros: { protein: 18, carbs: 14, fat: 10, calories: 220 },
    cookTime: 30,
    servings: 4,
    difficulty: 'Dễ',
    author: { name: 'Bà Ngoại', avatar: 'https://i.pravatar.cc/150?u=ngoai' },
    ingredients: [
      { name: 'Thịt heo bằm', amount: '200g', calories: 260, protein: 26, carbs: 0, fat: 18, category: 'meat' },
      { name: 'Cà rốt', amount: '100g', calories: 41, protein: 1, carbs: 10, fat: 0, category: 'vegetable' },
      { name: 'Khoai tây', amount: '150g', calories: 116, protein: 2, carbs: 27, fat: 0, category: 'vegetable' },
      { name: 'Hành tây', amount: '50g', calories: 20, protein: 0, carbs: 5, fat: 0, category: 'vegetable' },
      { name: 'Cà chua', amount: '100g', calories: 18, protein: 1, carbs: 4, fat: 0, category: 'vegetable' },
      { name: 'Hành lá', amount: '20g', calories: 6, protein: 0, carbs: 1, fat: 0, category: 'vegetable' },
    ],
    steps: [
      { order: 1, description: 'Rửa sạch rau củ. Thái hạt lựu.', image: null },
      { order: 2, description: 'Phi thơm hành tây, cho thịt bằm vào xào săn.', image: null },
      { order: 3, description: 'Thêm cà chua đảo nhuyễn. Cho nước sôi vào.', image: null },
      { order: 4, description: 'Cho cà rốt, khoai tây vào nấu 15 phút.', image: null },
    ],
    reviews: { avgRating: 4.4, total: 98 },
    isSaved: false,
  },

  // ── 4 recipe MỚI (đủ nguyên liệu — match với MOCK_PANTRY_ITEMS) ──
  {
    id: 'recipe_7',
    title: 'Trứng Chiên Cà Chua',
    image: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600',
    videoUrl: null,
    labels: ['Bữa sáng', 'Bữa phụ', 'Nhanh gọn', 'Giữ dáng'],
    macros: { protein: 14, carbs: 6, fat: 10, calories: 170 },
    cookTime: 10,
    servings: 1,
    difficulty: 'Dễ',
    author: { name: 'Mẹ Nấu Ăn', avatar: 'https://i.pravatar.cc/150?u=me' },
    ingredients: [
      { name: 'Trứng gà', amount: '2 quả', calories: 140, protein: 12, carbs: 1, fat: 10, category: 'dairy' },
      { name: 'Cà chua', amount: '1 quả', calories: 18, protein: 1, carbs: 4, fat: 0, category: 'vegetable' },
      { name: 'Dầu ăn', amount: '10ml', calories: 80, protein: 0, carbs: 0, fat: 9, category: 'condiment' },
      { name: 'Hành lá', amount: '10g', calories: 3, protein: 0, carbs: 1, fat: 0, category: 'vegetable' },
    ],
    steps: [
      { order: 1, description: 'Cà chua rửa sạch, thái múi cau. Hành lá thái nhỏ.', image: null },
      { order: 2, description: 'Đập trứng vào tô, thêm ít muối, đánh tan.', image: null },
      { order: 3, description: 'Phi thơm cà chua với dầu ăn, đổ trứng vào, xào đều tay.', image: null },
      { order: 4, description: 'Rắc hành lá, dùng nóng với cơm trắng.', image: null },
    ],
    reviews: { avgRating: 4.1, total: 67 },
    isSaved: false,
  },
  {
    id: 'recipe_8',
    title: 'Súp Bông Cải Xanh',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600',
    videoUrl: null,
    labels: ['Bữa tối', 'Giữ dáng', 'Dễ tiêu'],
    macros: { protein: 10, carbs: 14, fat: 8, calories: 160 },
    cookTime: 25,
    servings: 2,
    difficulty: 'Dễ',
    author: { name: 'Chef Healthy', avatar: 'https://i.pravatar.cc/150?u=healthy' },
    ingredients: [
      { name: 'Bông cải xanh', amount: '200g', calories: 68, protein: 6, carbs: 14, fat: 1, category: 'vegetable' },
      { name: 'Sữa tươi', amount: '200ml', calories: 130, protein: 6, carbs: 10, fat: 7, category: 'dairy' },
      { name: 'Dầu ăn', amount: '10ml', calories: 80, protein: 0, carbs: 0, fat: 9, category: 'condiment' },
      { name: 'Hành lá', amount: '10g', calories: 3, protein: 0, carbs: 1, fat: 0, category: 'vegetable' },
    ],
    steps: [
      { order: 1, description: 'Bông cải xanh rửa sạch, cắt miếng vừa ăn.', image: null },
      { order: 2, description: 'Luộc bông cải trong nước sôi 5 phút, vớt ra.', image: null },
      { order: 3, description: 'Cho bông cải và sữa tươi vào máy xay, xay nhuyễn.', image: null },
      { order: 4, description: 'Đổ súp vào nồi, nấu sôi lại, nêm muối, tiêu. Rắc hành lá.', image: null },
    ],
    reviews: { avgRating: 4.3, total: 45 },
    isSaved: false,
  },
  {
    id: 'recipe_9',
    title: 'Gà Xào Cà Rốt',
    image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600',
    videoUrl: null,
    labels: ['Bữa trưa', 'Tăng cơ', 'Gia đình'],
    macros: { protein: 32, carbs: 12, fat: 10, calories: 290 },
    cookTime: 20,
    servings: 2,
    difficulty: 'Dễ',
    author: { name: 'Chef Gym', avatar: 'https://i.pravatar.cc/150?u=gym' },
    ingredients: [
      { name: 'Ức gà', amount: '200g', calories: 220, protein: 46, carbs: 0, fat: 5, category: 'meat' },
      { name: 'Cà rốt', amount: '100g', calories: 41, protein: 1, carbs: 10, fat: 0, category: 'vegetable' },
      { name: 'Dầu ăn', amount: '15ml', calories: 120, protein: 0, carbs: 0, fat: 14, category: 'condiment' },
      { name: 'Hành lá', amount: '15g', calories: 5, protein: 0, carbs: 1, fat: 0, category: 'vegetable' },
    ],
    steps: [
      { order: 1, description: 'Ức gà rửa sạch, thái sợi. Cà rốt gọt vỏ, thái sợi.', image: null },
      { order: 2, description: 'Ướp gà với muối, tiêu 10 phút.', image: null },
      { order: 3, description: 'Phi thơm hành trắng, cho gà vào xào săn.', image: null },
      { order: 4, description: 'Cho cà rốt vào xào thêm 5 phút. Rắc hành lá.', image: null },
    ],
    reviews: { avgRating: 4.5, total: 112 },
    isSaved: true,
  },
  {
    id: 'recipe_10',
    title: 'Canh Trứng Cà Chua',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600',
    videoUrl: null,
    labels: ['Bữa tối', 'Gia đình', 'Dễ làm'],
    macros: { protein: 12, carbs: 8, fat: 8, calories: 150 },
    cookTime: 15,
    servings: 2,
    difficulty: 'Dễ',
    author: { name: 'Bà Ngoại', avatar: 'https://i.pravatar.cc/150?u=ngoai2' },
    ingredients: [
      { name: 'Trứng gà', amount: '2 quả', calories: 140, protein: 12, carbs: 1, fat: 10, category: 'dairy' },
      { name: 'Cà chua', amount: '2 quả', calories: 36, protein: 2, carbs: 8, fat: 0, category: 'vegetable' },
      { name: 'Dầu ăn', amount: '10ml', calories: 80, protein: 0, carbs: 0, fat: 9, category: 'condiment' },
      { name: 'Hành lá', amount: '10g', calories: 3, protein: 0, carbs: 1, fat: 0, category: 'vegetable' },
    ],
    steps: [
      { order: 1, description: 'Cà chua rửa sạch, bổ múi cau. Đánh tan trứng.', image: null },
      { order: 2, description: 'Phi thơm cà chua với dầu ăn, đảo đến khi nhuyễn.', image: null },
      { order: 3, description: 'Cho 500ml nước sôi vào, nêm gia vị.', image: null },
      { order: 4, description: 'Từ từ đổ trứng vào, khuấy nhẹ. Tắt bếp, rắc hành lá.', image: null },
    ],
    reviews: { avgRating: 4.2, total: 78 },
    isSaved: false,
  },
];

export const RECIPE_FILTERS = [
  { id: 'all', label: 'Tất cả' },
  { id: 'easy', label: 'Dễ' },
  { id: 'medium', label: 'Trung bình' },
  { id: 'hard', label: 'Khó' },
  { id: 'snack', label: 'Bữa phụ' },
  { id: 'breakfast', label: 'Bữa sáng' },
  { id: 'lunch', label: 'Bữa trưa' },
  { id: 'dinner', label: 'Bữa tối' },
  { id: 'lowcarb', label: 'Low Carb' },
  { id: 'highprotein', label: 'High Protein' },
];

export const REVIEW_TAGS = ['Ngon', 'Dễ làm', 'Tốn thờigian', 'Nguyên liệu dễ tìm', 'Phù hợp giảm cân', 'Ngon hơn mong đợi'];